Repository aiplanethub/genai-stack, pull requests merged in 2023-10, with the labels that each got.

#58 Code to conduct
  CODE_OF_CONDUCT.rst
  documentation/v0.2.0/example-use-cases/chat-on-webpage.md
Labels: help wanted

#79 Add api for model component
  genai_stack/constant.py
  genai_stack/genai_server/models/model_models.py
  genai_stack/genai_server/routers/model_routes.py
  genai_stack/genai_server/server.py
  genai_stack/genai_server/services/model_service.py
Labels: approved, component;apis

#64 Remove commented code & replace llm_stack with genai_stack
  assets/config_custom_chromadb.json
  assets/etl.json
  genai_stack/genai_stack.py
  genai_stack/model/__init__.py
  genai_stack/model/server.py
  genai_stack/retriever/base.py
  genai_stack/retriever/langchain.py
Labels: approved

#73 Make docstring style consistent in gpt3_5
  genai_stack/model/gpt3_5.py
Labels: approved
